// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import Comments__EditController from "./comments/edit_controller"
application.register("comments--edit", Comments__EditController)

import Comments__NewController from "./comments/new_controller"
application.register("comments--new", Comments__NewController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
